# Generated by Django 2.2.4 on 2020-03-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
