# Generated by Django 2.2.4 on 2020-04-06 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0002_income_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='expense.Sub_Category'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
