# Generated by Django 2.2.4 on 2020-04-11 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0009_data_month_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_year', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='month_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon', to='expense.Month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='monthly_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='monthy_expenditure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='year_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yr', to='expense.Year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='annual_expenditure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='year',
            name='annual_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.IntegerField(max_length=4),
        ),
    ]
