# Generated by Django 2.2.4 on 2020-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_auto_20200412_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.IntegerField(),
        ),
    ]
