# Generated by Django 2.2.4 on 2020-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_auto_20200412_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
